<<<<<<< HEAD:api_yamdb/users/migrations/0002_auto_20221218_1125.py
# Generated by Django 3.2 on 2022-12-18 11:25
=======
# Generated by Django 3.2 on 2022-12-17 09:56
>>>>>>> origin/feature/teammate2:api_yamdb/users/migrations/0003_auto_20221217_0956.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
