# Generated by Django 3.2 on 2022-12-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
        ('users', '0002_auto_20221216_0802'),
    ]

    operations = [
    ]
