# Generated by Django 3.2 on 2022-12-17 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0005_auto_20221217_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 17, 11, 43, 48, 133653)),
        ),
    ]
